name: Create quote of the day
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Create quote of the day
        run: python create.py
      - name: Format HTML file
        run: |
          sudo apt-get install tidy
          tidy -config .tidyrc -o index.html index.html
      - name: Commit files
        run: |
          git config --local user.email "simon@simonrijntjes.nl"
          git config --local user.name "Simon Rijntjes"
          git add .
          git commit -m "Updated the quote of the day! :tada:"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
